name: cashgo
description: A starter POS desktop app (admin + cashier) built with Flutter.
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.8
  path: ^1.8.3
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # Uncomment the assets lines below after adding actual files in these folders
  # assets:
  #   - assets/images/
  #   - assets/icons/
