name: Build Flutter Windows App

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable Windows support
        run: flutter config --enable-windows-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows release
        run: flutter build windows --release

      - name: Create zip file
        run: Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath CashGo-windows.zip

      # ========== CREATE RELEASE (pass token correctly) ==========
      - name: Create Release (with PAT)
        id: create_release
        uses: actions/create-release@v1
        with:
          # إذا ستستخدم GITHUB_TOKEN بدل PAT فغيّر السطر أدناه إلى ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.PAT_TOKEN }}
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Windows build
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: CashGo-windows.zip
          asset_name: CashGo-windows.zip
          asset_content_type: application/zip
        env:
          # تأكد أن نفس التوكن متوفر كمتغير بيئـي لو احتاجت الخطوة ذلك
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
