name: Build Flutter Windows App

on:
  push:
    branches: [ master, ci-windows-build ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable Windows support
        run: flutter config --enable-windows-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows release
        run: flutter build windows --release

      - name: Create zip file
        run: Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath CashGo-windows.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: CashGo-windows
          path: CashGo-windows.zip
